### get pokemon info
GET http://localhost:3000/pokemon/dito

### create pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "name": "alsh",
  "type": "ghot",
  "moves": [
    "transform"
  ]
}